name: Deploy to Netlify

on:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  APP_NAME: zero

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout data
        uses: actions/checkout@v3
        with:
          repository: panghaibin/RiskLevelAPI
#          path: RiskLevelAPI
          ref: api
#      - run: git checkout api

      - name: Show
        run: cat info.json
